services:
  web:
    build:
      context: .
    container_name: laravel_web
    ports:
      - "80:80"  # Render will detect port 80
    volumes:
      - .:/var/www
    networks:
      - laravel
    environment:
      APP_URL: http://localhost
      # Optionally load secrets here or rely on .env
    command: ["/entrypoint.sh"]

networks:
  laravel:
